language: java 
sudo: false 
install: true 
addons:
   sonarcloud:
      organization: "kurromat-github" 
      token: "5e62dd38d6049fa5a3276ff905bce2a18e0f1852" 
jdk:
   - oraclejdk8 
script:
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar 
cache: 
   directories: 
      - '$HOME/.m2/repository' 
      - '$HOME/.sonar/cache' 
